### ISSUE TITLE
Backticks and apostrophe usage in markdown, general observation and recommendation

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#1]
**Recommendation:** In markdown text where the intention is to allow 'type text' or other autotype-into-VM features, it is likely more standard to format using the 'backtick' (on US keyboard, the key w/tilde and backtick) as opposed to the apostrophe (US keyboard = quotation mark and apostrophe).  

The reason for this is various ALH's may have their own proprietary methods to allow 'typetext', however methods that are more generic - such as Github's method - are more likely to be ALH-agnostic, and also not require as much manual or other re-formatting by ALHs.   

In most places where a student might need to type something into the VM, it appears no backticks are in use at all, for example:

14. In the Scrap percentage field, enter **30**.

This would preferably be formatted like so:

14. In the Scrap percentage field, enter **`30`**.

In other places it appears an attempt was made to use apostrophes (with slash character to prevent display) in particular in https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/blob/master/Instructions/Labs/M3%20Implement%20production%20methods_1B.md (but also in other docs) for example as  seen in Exercise#7:

## Currently looks like:

3. In the **Product number** field, enter or select **\'P6100\'**.

4. In the **Product name** field, enter or select '**Orange Juice\'**.

5. In the **Search name** field, enter or select **\'Orange Juice\'**.

6. In the **Item model group** field, enter or select FEFO.

## Preferably formatted like:

3. In the **Product number** field, enter or select **`P6100`**.

4. In the **Product name** field, enter or select **`Orange Juice`**.

5. In the **Search name** field, enter or select **`Orange Juice`**.

6. In the **Item model group** field, enter or select **`FEFO`**.

(example of formatting, stuck in a code block to defeat GH editor auto-formatting)

```
**`P6100`**
```

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 3 / Case study 1B / Exercise 7 Step 3-6. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
Thanks again for providing insight on this. The tick marks have been removed to avoid confusion. 

![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/104943975/97c8f40a-7859-431c-a9a7-193a9f973edd)
