### ISSUE TITLE
Missing Step 

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#2]
# [M2 Configure production prerequisites.md](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/blob/master/Instructions/Labs/M2%20Configure%20production%20prerequisites.md)

#### Step: 16

Step 16 appears to be blank. 

![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/72228536/aa42058f-dda8-4dca-b37b-bbfd6119e32e)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1A / Exercise 14 Step 16. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
Thanks again for providing insight on this. The lab instructions have been updated accordingly.
