### ISSUE TITLE
Intercompany planning group missing

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#3]
[M4 Configure production control_masterplanning.md](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/blob/master/Instructions/Labs/M4%20Configure%20production%20control_masterplanning.md)

#### Step: 03

Description of issue

3.	Select 60 for Intercompany planning group.

Used 40 instead as depicted in the trainer files due to 60 missing.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 4 / Case study 2 / Exercise 2 Step 03. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
Thanks again for providing insight on this. I was able to replicate this issue while running the intercompany master plan. The intercompany planning group to choose is based on the group previously created under 'Create an intercompany planning group'. To minimize the confusion, I've update the lab instructions to reflect the updates to the appropriate value to use. 

![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/104943975/4e5f98ce-2da0-4e59-9edc-ffc515b7a3a7)
