### ISSUE TITLE
Facing Issue while Saving the Production Prerequisites 

### ISSUE THREAD

**Issue by ahmadfaizan1** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#5]
# Module: 02
#### Step: 06-22
Description of issue
![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/87553541/8c068a85-53ec-4b2d-92e9-448417720865)
While saving the Production Prerequisites we are facing this issue.
Repro steps:

Select Route on the Action Pane then in the Maintain group, select Route details.

Select New.

In the Operation field, enter or select Assembly.

In the Scrap Percentage field, enter 20.

In the Link type field, select Soft.

Select New.

In the Oper. No. field, enter 20.

In the Operation field, enter or select Padding.

In the Scrap percentage field, enter 30.

In the Link type field, select Hard.

Select New.

In the Oper. No. field, enter 30.

In the Priority field, select Primary.

In the Operation field, enter or select Packing.

Refresh the page.

Select Save.

Close all pages.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1A / Exercise ? Step 06-22. We are reviewing this and will provide an update once a resolution is in place. Please elaborate as to which exercise this issue is in reference to along with repo steps

**Comment by ahmadfaizan1** [comment]
> Thanks for reporting this on GitHub! Module 2 / Case study 1A / Exercise **?** Step 06-22. We are reviewing this and will provide an update once a resolution is in place. Please elaborate as to which exercise this issue is in reference to along with repo steps.
Module 2: Configure production prerequisites.
Exercise 4: Create an operation, assign relations, and create a route.
Step 06-22

Select Route on the Action Pane then in the Maintain group, select Route details.

Select New.

In the Operation field, enter or select Assembly.

In the Scrap Percentage field, enter 20.

In the Link type field, select Soft.

Select New.

In the Oper. No. field, enter 20.

In the Operation field, enter or select Padding.

In the Scrap percentage field, enter 30.

In the Link type field, select Hard.

Select New.

In the Oper. No. field, enter 30.

In the Priority field, select Primary.

In the Operation field, enter or select Packing.

Refresh the page.

Select Save.

Close all pages.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! I did not run into any issues during replication with errors on the Route details page. The route is created prior to creating the route relation as there has to be route details and assignments for the operation. The route contains the order of operations which sit within the route. The route group is automatically added to the grid after the first record is created for the Assembly operation. 

It seems that you skipped steps 11 through 15 during the exercise. Please ensure to follow the instructions for completing the operations according to the steps. Please retry initiating the steps again. 

![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/104943975/e8716f70-0de5-4dba-9f46-0d0794e711de)
