### ISSUE TITLE
Module 3-1b Add Co-Products and By-Products with Cost Allocation - unable to find the By-product cost allocation percent column

### ISSUE THREAD

**Issue by MuhammadTalhaSatti** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#6]
# Module: 03
#### Step: 14

Description of issue

I am unable to find the By-product cost allocation percent column. Please see the screenshot below:

![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/79168926/534fdef0-4b05-40e8-9c2a-a5bd80ae6cb5)

Repro steps:

1. Follow the steps till step number 14
1. See that there is no column with the name By-product cost allocation percent.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 3 / Case study 1B / Exercises 3. The instruction steps have been updated accordingly.
