### ISSUE TITLE
M2 Case Study 1A - Unable to find resource 5110

### ISSUE THREAD

**Issue by Yiizo** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#7]
# M2 Case Study 1A Configure production prerequisites

Description of issue:

Unable to find resource **5110**

**Assign resources to capability**

    Go to Organization administration > Resources > Resource capabilities.

    Select GTL-Assembly from the list of capabilities.

    Select Add from the toolbar.

    Select **5110**, Assembly worker 1, in the Resource field.

![5110](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/98825246/0ad47ceb-7063-4bd6-9017-6b0262a1e90d)

The only one that is available is Resource **00020** Julia Funderburk.

![00020](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/98825246/289a5015-cff4-4684-937c-d766ea9a9efc)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1A / Exercise 3 Step 04. Please update the legal entity in the upper right corner from DAT to USMF to complete the exercise. 
![image](https://github.com/MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert/assets/104943975/1cf4f46a-2466-4fc4-ac53-ba18f3137fe9)
